Repository antvis/Dipper, pull requests merged in 2022-06, with the labels that each got.

#158 fix: 修复依赖注入容器复用的情况
  packages/layout/src/layout/Container/Context.tsx
Labels: PR: unreviewed, bugfix

#159 feat: 新增 LIContainer 容器
  docs/dev/LI/demos/configs/config.ts
  docs/dev/LI/demos/configs/xihu-district.json
  docs/dev/LI/demos/index.tsx
  docs/dev/LI/index.md
  package.json
  packages/core/src/services/config/IConfigService.ts
  packages/core/src/widgetFactory.tsx
  packages/layout/src/BaseWidget/index.tsx
  packages/pc/package.json
  packages/pc/src/layout/LIContainer/MapContainer/Map/index.less
  packages/pc/src/layout/LIContainer/MapContainer/Map/index.tsx
  packages/pc/src/layout/LIContainer/MapContainer/index.less
  packages/pc/src/layout/LIContainer/MapContainer/index.tsx
  packages/pc/src/layout/LIContainer/MapControls/index.less
  packages/pc/src/layout/LIContainer/MapControls/index.tsx
  packages/pc/src/layout/LIContainer/index.less
  packages/pc/src/layout/LIContainer/index.tsx
  packages/pc/src/layout/index.ts
  tsconfig.json
Labels: PR: unreviewed, feature

#162 chore: 给 pre-coomit 添加打包 hook & 修复代码格式问题
  .github/workflows/lint.yml
  .husky/pre-commit
  packages/core/src/services/layer/LayerGroup.ts
  packages/dipper/src/index.ts
  packages/layout/src/layout/Map/index.tsx
  packages/layout/src/widgets/index.ts
  packages/layout/src/widgets/popup/index.tsx
Labels: PR: unreviewed, ignore-for-release

#164 fix: 修复 globalmodel 对象引用问题
  docs/dev/layout/configs/config.ts
  packages/core/package.json
  packages/core/src/services/config/ConfigService.ts
  packages/dipper/package.json
  packages/layout/package.json
  packages/layout/src/hooks/useGlobalModel.ts
  packages/mobile/package.json
  packages/pc/package.json
  packages/widgets/package.json
Labels: PR: reviewed-approved, bugfix

#163 fix: global model
  docs/basis-api/demo/control.tsx
  docs/basis-components/layer/demo/grid-layer/config/config.ts
  docs/basis-components/layer/demo/grid-layer/index.tsx
  docs/basis-components/layer/demo/grid-layer/widgets/GridLayer.tsx
  docs/basis-components/layer/demo/image-layer/config/config.ts
  docs/basis-components/layer/demo/image-layer/index.tsx
  docs/dev/layout/app.tsx
  docs/dev/layout/configs/config.ts
  docs/dev/layout/widgets/POILayer.tsx
  packages/core/package.json
  packages/core/src/services/config/ConfigService.ts
  packages/core/src/services/config/IConfigService.ts
  packages/core/src/services/widgets/IWidgetsService.ts
  packages/dipper/package.json
  packages/layout/package.json
  packages/layout/src/hooks/useGlobalModel.ts
  packages/mobile/package.json
  packages/pc/package.json
  packages/pc/src/layout/Toolbar/index.less
  packages/pc/src/layout/Toolbar/index.tsx
  packages/widgets/package.json
Labels: PR: reviewed-approved, bugfix

#165 fix: 修复 useGlobalModel 类型问题
  docs/basis-api/hooks/useGlobalModel.md
  docs/dev/layout/app.tsx
  docs/dev/layout/configs/config.ts
  packages/layout/src/hooks/useGlobalModel.ts
Labels: PR: reviewed-approved, bugfix

#167 docs: 移除文档冗余内容
  docs/basis-api/index.md
  docs/basis-components/container/base.md
  docs/basis-components/layout/index.md
  docs/guide/quick-start.md
  docs/guide/tutorials/index.md
  docs/mobile/case/index.md
  docs/mobile/components.md
  docs/mobile/config.md
  docs/mobile/hooks.md
  docs/mobile/index.md
  docs/pc/components.md
  docs/pc/components/index.md
  docs/pc/hooks.md
Labels: documentation, PR: unreviewed

#168 fix: 解决 antd 样式全局引入问题
  packages/widgets/src/Filter/CitySelect.tsx
  packages/widgets/src/NavBar.tsx
Labels: PR: unreviewed, bugfix
