Repository antvis/Dipper, pull requests merged in 2022-04, with the labels that each got.

#132 docs: 修复网站文档打包问题
  .umirc.ts
Labels: PR: unreviewed

#133 refactor: 兼容修改不规范单复数的 API
  docs/basis-api/config.md
  docs/basis-api/core.md
  docs/basis-api/hooks/useConfigService.md
  docs/basis-api/hooks/useGlobalModel.md
  docs/basis-api/hooks/useLayerGroup.md
  docs/basis-api/hooks/useSceneService.md
  docs/basis-api/hooks/useWidgets.md
  docs/dev/demo/index.tsx
  docs/dev/toolbar/index.tsx
  docs/guide/tutorials/index.md
  docs/pc/case/demo/analysis/widgets/Filter.tsx
  docs/pc/case/demo/analysis/widgets/GridLayer.tsx
  docs/pc/case/demo/task/widgets/GridLayer.tsx
  packages/core/src/services/config/ConfigService.ts
  packages/core/src/services/config/IConfigService.ts
  packages/core/src/services/widgets/IWidgetsService.ts
  packages/core/src/services/widgets/widget.ts
  packages/layout/src/hooks/index.ts
  packages/layout/src/hooks/useConfigService.ts
  packages/layout/src/hooks/useFilterValue.ts
  packages/layout/src/hooks/useWidget.ts
  packages/layout/src/hooks/useWidgets.ts
  packages/widgets/src/Draw/index.tsx
  packages/widgets/src/Filter/CitySelect.tsx
  packages/widgets/src/Filter/ConfigFilter.tsx
  packages/widgets/src/Filter/FunnelFilter.tsx
  packages/widgets/src/Filter/Select.tsx
  packages/widgets/src/PanelTabContent/Content.tsx
  packages/widgets/src/Search/index.tsx
Labels: PR: unreviewed

#135 docs: 基础 API 文档，首页添加，删除重复文档
  docs/basis-api/index.md
  docs/basis-components/container/base.md
  docs/basis-components/index.md
  docs/basis-components/layer/demo/grid-layer/config/config.ts
  docs/basis-components/layer/demo/grid-layer/index.tsx
  docs/basis-components/layer/demo/grid-layer/widgets/GridLayer.tsx
  docs/basis-components/layer/demo/grid-layer/widgets/index.ts
  docs/basis-components/layer/demo/image-layer/config/config.ts
  docs/basis-components/layer/demo/image-layer/index.tsx
  docs/basis-components/layer/demo/image-layer/widgets/ImageLayer.tsx
  docs/basis-components/layer/demo/image-layer/widgets/index.tsx
  docs/basis-components/layer/demo/layer-group/config/config.ts
  docs/basis-components/layer/demo/layer-group/index.tsx
  docs/basis-components/layer/demo/layer-group/widgets/CustomLayerGroup.ts
  docs/basis-components/layer/demo/layer-group/widgets/Layer.tsx
  docs/basis-components/layer/demo/layer-group/widgets/index.tsx
  docs/basis-components/layer/demo/marker-layer/config/config.ts
  docs/basis-components/layer/demo/marker-layer/index.tsx
  docs/basis-components/layer/demo/marker-layer/widgets/MarkerLayer.tsx
  docs/basis-components/layer/demo/marker-layer/widgets/index.tsx
  docs/basis-components/layer/demo/point-layer/color/config/config.ts
  docs/basis-components/layer/demo/point-layer/color/index.tsx
  docs/basis-components/layer/demo/point-layer/color/widgets/PointLayer.tsx
  docs/basis-components/layer/demo/point-layer/color/widgets/index.tsx
  docs/basis-components/layer/demo/point-layer/hover/config/config.ts
  docs/basis-components/layer/demo/point-layer/hover/index.tsx
  docs/basis-components/layer/demo/point-layer/hover/widgets/MyPanel.tsx
  docs/basis-components/layer/demo/point-layer/hover/widgets/PointLayer.tsx
  docs/basis-components/layer/demo/point-layer/hover/widgets/index.tsx
  docs/basis-components/layer/grid-layer.md
  docs/basis-components/layer/image-layer.md
  docs/basis-components/layer/layer-group.md
  docs/basis-components/layer/line-layer.md
  docs/basis-components/layer/marker-layer.md
  docs/basis-components/layer/point-layer.md
  docs/basis-components/layout/index.md
  docs/basis-components/widgets/index.md
  docs/guide/tutorials/index.md
  docs/index.md
Labels: documentation, PR: unreviewed

#136 fix: 修复接口定义方法名称错误问题
  packages/core/src/services/config/IConfigService.ts
Labels: PR: unreviewed, bugfix

#137 docs: 更新点图层 Demo
  docs/basis-api/layer/demo/marker-layer/index.tsx
  docs/basis-api/layer/demo/point-layer/color/config/config.ts
  docs/basis-api/layer/demo/point-layer/color/index.tsx
  docs/basis-api/layer/demo/point-layer/hover/config/config.ts
  docs/basis-api/layer/demo/point-layer/hover/index.tsx
  docs/mobile/index.md
  docs/pc/case/demo/task/index.tsx
Labels: documentation, PR: unreviewed

#138 fix: 修复图层各个demo中的title配置错误问题
  docs/basis-api/layer/demo/grid-layer/config/config.ts
  docs/basis-api/layer/demo/image-layer/config/config.ts
  docs/basis-api/layer/demo/layer-group/config/config.ts
  docs/basis-api/layer/demo/marker-layer/config/config.ts
Labels: PR: reviewed-approved, bugfix

#141 doc: 修改 useConfigService 引用错误问题
  docs/guide/tutorials/index.md
Labels: PR: reviewed-approved

#142 doc: 修改类型引用路径、删除重复的变量
  docs/basis-api/hooks/useLayerGroup.md
  docs/basis-api/layer/demo/marker-layer/widgets/MarkerLayer.tsx
Labels: PR: reviewed-approved

#143 docs: 配置项文档、config 增加 addControl/removeControl方法
  docs/pc/case/demo/analysis/configs/config.ts
  docs/pc/case/demo/analysis/widgets/GridLayer.tsx
  docs/pc/case/demo/task/widgets/GridLayer.tsx
  docs/pc/index.md
  docs/pc/layout.md
  packages/core/src/services/config/ConfigService.ts
  packages/core/src/services/config/IConfigService.ts
  packages/core/src/services/panel/IPanelService.ts
  packages/pc/src/layout/MapControl/index.less
  packages/pc/src/layout/MapControl/index.tsx
Labels: documentation, PR: partially-approved

#144 fix: lint 错误未使用变量 & mapcontrol 导出问题
  packages/core/src/container.ts
  packages/layout/src/hooks/useSceneService.ts
  packages/layout/src/layout/Container/Context.tsx
  packages/layout/src/layout/Layer/index.tsx
  packages/layout/src/layout/Map/index.tsx
  packages/layout/src/widgets/layer/GridLayer/GridLayerGroup.ts
  packages/mobile/src/layout/MapControl/index.tsx
  packages/mobile/src/layout/Panel/index.tsx
  packages/mobile/src/layout/Toolbar/index.tsx
  packages/mobile/src/layout/index.tsx
  packages/pc/src/layout/Container/index.tsx
  packages/pc/src/layout/Header/index.tsx
  packages/pc/src/layout/MapControls/index.tsx
  packages/pc/src/layout/Panel/ToggleButton.tsx
  packages/pc/src/layout/Toolbar/index.tsx
  packages/pc/src/layout/index.ts
  packages/widgets/src/Draw/index.tsx
  packages/widgets/src/Legend/ClassifyColor.tsx
  packages/widgets/src/Legend/MultiClassifyColor.tsx
  packages/widgets/src/Location/index.tsx
  packages/widgets/src/MeshName/index.tsx
  packages/widgets/src/NavBar.tsx
  packages/widgets/src/Search/index.tsx
Labels: PR: reviewed-approved, bugfix

#145 chore: 解决项目多包引入 Definition 问题
  tsconfig.json
Labels: PR: reviewed-approved, ignore-for-release

#146 chore: 避免与 npm script hook 冲突修改打包 script
  lerna.json
  package.json
Labels: PR: reviewed-approved, ignore-for-release

#148 fix: 修复类型入口文件地址
  packages/dipper/package.json
  packages/layout/package.json
  packages/mobile/package.json
  packages/pc/package.json
  packages/widgets/package.json
Labels: PR: reviewed-approved, bugfix

#149 fix: 修复 peerDependencies 依赖项
  docs/guide/quick-start.md
  docs/guide/tutorials/index.md
  packages/mobile/package.json
  packages/pc/package.json
Labels: PR: reviewed-approved, bugfix
