Repository antvis/Dipper, pull requests merged in 2022-05, with the labels that each got.

#151 Feat: 完善Point、Image、Grid 三种图层的API文档
  docs/basis-api/layer/demo/grid-layer/index.tsx
  docs/basis-api/layer/demo/image-layer/widgets/ImageLayer.tsx
  docs/basis-api/layer/grid-layer.md
  docs/basis-api/layer/image-layer.md
  docs/basis-api/layer/point-layer.md
  packages/layout/src/widgets/layer/ImageLayer/ImageLayerGroup.ts
Labels: PR: reviewed-approved

#152 feat: layergroup 支持 source 配置项
  packages/core/src/services/layer/ILayerService.ts
  packages/core/src/services/layer/LayerGroup.ts
  packages/layout/src/widgets/layer/PointLayer/PointLayerGroup.ts
Labels: PR: reviewed-approved, feature

#153 fix: source option & 添加 tnpm async
  package.json
  packages/core/package.json
  packages/core/src/services/layer/LayerGroup.ts
  packages/dipper/package.json
  packages/layout/package.json
  packages/mobile/package.json
  packages/pc/package.json
  packages/widgets/package.json
Labels: PR: reviewed-approved, bugfix

#154 fix: 文档目录 & source 更新bug
  docs/basis-api/layer/demo/point-layer/color/widgets/PointLayer.tsx
  docs/basis-components/layer/demo/grid-layer/config/config.ts
  docs/basis-components/layer/demo/grid-layer/index.tsx
  docs/basis-components/layer/demo/grid-layer/widgets/GridLayer.tsx
  docs/basis-components/layer/demo/grid-layer/widgets/index.ts
  docs/basis-components/layer/demo/image-layer/config/config.ts
  docs/basis-components/layer/demo/image-layer/index.tsx
  docs/basis-components/layer/demo/image-layer/widgets/ImageLayer.tsx
  docs/basis-components/layer/demo/image-layer/widgets/index.tsx
  docs/basis-components/layer/demo/layer-group/config/config.ts
  docs/basis-components/layer/demo/layer-group/index.tsx
  docs/basis-components/layer/demo/layer-group/widgets/CustomLayerGroup.ts
  docs/basis-components/layer/demo/layer-group/widgets/Layer.tsx
  docs/basis-components/layer/demo/layer-group/widgets/index.tsx
  docs/basis-components/layer/demo/marker-layer/config/config.ts
  docs/basis-components/layer/demo/marker-layer/index.tsx
  docs/basis-components/layer/demo/marker-layer/widgets/MarkerLayer.tsx
  docs/basis-components/layer/demo/marker-layer/widgets/index.tsx
  docs/basis-components/layer/demo/point-layer/color/config/config.ts
  docs/basis-components/layer/demo/point-layer/color/index.tsx
  docs/basis-components/layer/demo/point-layer/color/widgets/PointLayer.tsx
  docs/basis-components/layer/demo/point-layer/color/widgets/index.tsx
  docs/basis-components/layer/demo/point-layer/hover/config/config.ts
  docs/basis-components/layer/demo/point-layer/hover/index.tsx
  docs/basis-components/layer/demo/point-layer/hover/widgets/MyPanel.tsx
  docs/basis-components/layer/demo/point-layer/hover/widgets/PointLayer.tsx
  docs/basis-components/layer/demo/point-layer/hover/widgets/index.tsx
  docs/basis-components/layer/grid-layer.md
  docs/basis-components/layer/image-layer.md
  docs/basis-components/layer/layer-group.md
  docs/basis-components/layer/line-layer.md
  docs/basis-components/layer/marker-layer.md
  docs/basis-components/layer/point-layer.md
  packages/core/src/services/layer/LayerGroup.ts
  packages/layout/src/widgets/layer/PointLayer/PointLayerGroup.ts
Labels: PR: reviewed-approved, bugfix

#155 chore: 确保 githooks 内置成功
  package.json
Labels: PR: unreviewed, ignore-for-release

#156 fix: image layergroup
  docs/basis-components/layer/demo/image-layer/widgets/ImageLayer.tsx
  packages/core/src/services/layer/LayerGroup.ts
  packages/layout/src/widgets/layer/ImageLayer/ImageLayerGroup.ts
  packages/layout/src/widgets/layer/PointLayer/PointLayerGroup.ts
  packages/widgets/src/Legend/index.less
  packages/widgets/src/TabsContent/index.tsx
Labels: PR: reviewed-approved

#157 build: 修复打包问题
  .gitignore
  packages/core/.fatherrc.ts
  packages/core/package.json
  packages/dipper/.fatherrc.ts
  packages/dipper/package.json
  packages/layout/.fatherrc.ts
  packages/layout/package.json
  packages/layout/src/widgets/layer/ImageLayer/ImageLayerGroup.ts
  packages/layout/src/widgets/layer/PointLayer/PointLayerGroup.ts
  packages/mobile/.fatherrc.ts
  packages/mobile/package.json
  packages/pc/.fatherrc.ts
  packages/pc/package.json
  packages/widgets/.fatherrc.ts
  packages/widgets/package.json
  packages/widgets/src/Filter/ConfigFilter.tsx
  tsconfig.json
Labels: PR: unreviewed
